// Presentation bundler: turns a declarative bundle definition into versioned,
// deterministic, self-contained CSS release artifacts plus a manifest and a
// sha256sum-compatible checksum file.
//
// usage: PresentationBundler <bundle.json> <package.json>
//
// Determinism: inputs are read as UTF-8, line endings are normalized to LF,
// nothing time- or machine-dependent is written, and files are listed in
// definition order. Two runs over the same sources produce identical bytes.

open System
open System.IO
open System.Security.Cryptography
open System.Text
open System.Text.Json
open System.Text.Json.Nodes

type Artifact =
    { File: string
      Description: string
      Sources: string list }

type Bundle =
    { Name: string
      Description: string
      OutputDirectory: string
      Artifacts: Artifact list }

type Built =
    { Artifact: Artifact
      Body: string
      Content: string
      Sha256: string
      Bytes: int }

exception BundleError of string

let fail message = raise (BundleError message)

let text (node: JsonNode | null) (name: string) =
    match node with
    | null -> fail $"bundle field '{name}' is required"
    | value -> value.GetValue<string>()

let parseBundle (path: string) : Bundle =
    let root =
        match JsonNode.Parse(File.ReadAllText path) with
        | null -> fail "bundle definition is empty"
        | node -> node.AsObject()

    match root["schemaVersion"] with
    | null -> fail "bundle schemaVersion is required"
    | v when v.GetValue<int>() <> 1 -> fail $"unsupported bundle schemaVersion {v}"
    | _ -> ()

    let artifacts =
        match root["artifacts"] with
        | null -> fail "bundle artifacts are required"
        | node ->
            node.AsArray()
            |> Seq.map (fun item ->
                let obj = (nonNull item).AsObject()
                { File = text obj["file"] "file"
                  Description = text obj["description"] "description"
                  Sources =
                    (nonNull obj["sources"]).AsArray()
                    |> Seq.map (fun s -> (nonNull s).GetValue<string>())
                    |> List.ofSeq })
            |> List.ofSeq

    { Name = text root["name"] "name"
      Description = text root["description"] "description"
      OutputDirectory = text root["outputDirectory"] "outputDirectory"
      Artifacts = artifacts }

let packageVersion (path: string) =
    match JsonNode.Parse(File.ReadAllText path) with
    | null -> fail "package.json is empty"
    | node -> text node["version"] "version"

let normalize (content: string) =
    content.Replace("\r\n", "\n").TrimEnd('\n') + "\n"

let sha256 (content: string) =
    Encoding.UTF8.GetBytes content
    |> SHA256.HashData
    |> Convert.ToHexString
    |> fun hex -> hex.ToLowerInvariant()

// A distributed artifact must work when copied anywhere: no @import, no
// relative url() references, and nothing executable.
let validateSelfContained (file: string) (content: string) =
    let lower = content.ToLowerInvariant()
    [ "@import", "imports another stylesheet"
      "<script", "contains markup"
      "javascript:", "contains a script URL"
      "expression(", "contains a CSS expression" ]
    |> List.tryFind (fun (needle, _) -> lower.Contains needle)
    |> Option.iter (fun (_, reason) -> fail $"{file} {reason}; release artifacts must be self-contained")

    let urls =
        RegularExpressions.Regex.Matches(content, @"url\(\s*['""]?(?<target>[^'"")\s]+)")
        |> Seq.map (fun m -> m.Groups["target"].Value)
        |> Seq.filter (fun target -> not (target.StartsWith("data:", StringComparison.OrdinalIgnoreCase)))
        |> List.ofSeq

    if not urls.IsEmpty then
        let listed = String.concat ", " urls
        fail $"{file} references external files ({listed}); release artifacts must be self-contained"

let build (root: string) (version: string) (bundle: Bundle) : Built list =
    let sourceBody (built: Map<string, Built>) (source: string) =
        match source.Split(':', 2) with
        | [| "artifact"; name |] ->
            match built.TryFind name with
            | Some previous -> $"/* --- artifact: {name} --- */\n" + previous.Body
            | None -> fail $"artifact '{name}' must be defined before it is referenced"
        | _ ->
            let path = Path.Combine(root, source)
            if not (File.Exists path) then fail $"bundle source '{source}' does not exist; run the Forma build first"
            $"/* --- source: {source} --- */\n" + normalize (File.ReadAllText path)

    let header (artifact: Artifact) =
        $"/*! Forma {version} | {artifact.File} | bundle {bundle.Name}\n    {artifact.Description}\n    Generated by tools/PresentationBundler. Do not edit; pin by version and sha256. */\n"

    bundle.Artifacts
    |> List.fold
        (fun (built: Map<string, Built>, ordered: Built list) artifact ->
            if built.ContainsKey artifact.File then fail $"duplicate artifact '{artifact.File}'"
            let body = artifact.Sources |> List.map (sourceBody built) |> String.concat "\n"
            let content = header artifact + "\n" + body
            validateSelfContained artifact.File content
            let result =
                { Artifact = artifact
                  Body = body
                  Content = content
                  Sha256 = sha256 content
                  Bytes = Encoding.UTF8.GetByteCount content }
            built.Add(artifact.File, result), ordered @ [ result ])
        (Map.empty, [])
    |> snd

let manifest (version: string) (bundle: Bundle) (built: Built list) =
    let artifacts = JsonArray()
    built
    |> List.iter (fun b ->
        let sources = JsonArray()
        b.Artifact.Sources |> List.iter (fun s -> sources.Add(JsonValue.Create s))
        let entry = JsonObject()
        entry["file"] <- JsonValue.Create b.Artifact.File
        entry["description"] <- JsonValue.Create b.Artifact.Description
        entry["bytes"] <- JsonValue.Create b.Bytes
        entry["sha256"] <- JsonValue.Create b.Sha256
        entry["sources"] <- sources
        artifacts.Add entry)
    let root = JsonObject()
    root["schemaVersion"] <- JsonValue.Create 1
    root["forma"] <- JsonValue.Create version
    root["bundle"] <- JsonValue.Create bundle.Name
    root["description"] <- JsonValue.Create bundle.Description
    root["releaseTag"] <- JsonValue.Create $"v{version}"
    root["artifacts"] <- artifacts
    root.ToJsonString(JsonSerializerOptions(WriteIndented = true)).Replace("\r\n", "\n") + "\n"

let checksums (built: Built list) =
    built
    |> List.map (fun b -> $"{b.Sha256}  {b.Artifact.File}\n")
    |> String.concat ""

[<EntryPoint>]
let main argv =
    try
        match argv with
        | [| bundlePath; packagePath |] ->
            let root = Environment.CurrentDirectory
            let bundle = parseBundle bundlePath
            let version = packageVersion packagePath
            let built = build root version bundle
            let output = Path.Combine(root, bundle.OutputDirectory)
            Directory.CreateDirectory output |> ignore
            built |> List.iter (fun b -> File.WriteAllText(Path.Combine(output, b.Artifact.File), b.Content))
            File.WriteAllText(Path.Combine(output, "forma-marketing.manifest.json"), manifest version bundle built)
            File.WriteAllText(Path.Combine(output, "forma-marketing.sha256"), checksums built)
            built |> List.iter (fun b -> printfn "%s  %s  %d bytes" b.Sha256 b.Artifact.File b.Bytes)
            printfn "bundle %s for Forma %s: %d artifacts" bundle.Name version built.Length
            0
        | _ ->
            eprintfn "usage: PresentationBundler <bundle.json> <package.json>"
            2
    with
    | BundleError message ->
        eprintfn "ERROR %s" message
        1
