// Canonical documentation metadata for implemented Forma patterns.
// Kept separate from the site renderer so catalog growth does not turn
// tools/build-site.mjs into a structural monolith.
export const componentMeta = {
  "marketing-shell": ["Marketing shell", "Marketing presentation", "Site content", "Reusable marketing-site frame: skip link, identity header with wrapping navigation, main content, and footer. Sites own content; the shell owns structure, focus, and responsive behavior."],
  "site-header": ["Site header", "Marketing presentation", "Site content", "Identity and primary navigation that wraps instead of hiding links, keeps 44px targets, and marks the current page with a non-color rule."],
  "hero": ["Hero", "Marketing presentation", "Site content", "A page's first region: one promise, one primary action, and optional supporting context that stacks below it in source order."],
  "section-heading": ["Section heading", "Marketing presentation", "Site content", "Labels a page section with an eyebrow, heading, framing sentence, and optional aside that wraps on narrow screens."],
  "card-grid": ["Card grid", "Marketing presentation", "Site content", "Ruled grid of cards with a column cap and content-driven column dropping; card links stretch without making the whole card the accessible name."],
  "facts": ["Facts", "Marketing presentation", "Site content", "Short claims with supporting detail as a description list in a ruled, auto-fitting grid."],
  "entry-index": ["Entry index", "Marketing presentation", "Site content", "Ordered linked entries (research areas, products) that regroup from four columns to one by container width."],
  "steps": ["Steps", "Marketing presentation", "Site content", "Numbered method or process using CSS counters on a native ordered list."],
  "badge": ["Badge", "Marketing presentation", "Site content", "Compact labels and metadata; status badges carry meaning in text with a redundant colored edge."],
  "cta": ["Call to action", "Marketing presentation", "Site content", "Closing call to action with one primary action, optionally on an inverse surface tone."],
  "code-sample": ["Code sample", "Marketing presentation", "Site content", "Technical sample in a captioned, keyboard-scrollable region that never widens the page."],
  "prose": ["Prose", "Marketing presentation", "Site content", "Long-form content constrained to the reading measure with underlined links and consistent heading rhythm."],
  "site-footer": ["Site footer", "Marketing presentation", "Site content", "Closing identity, actions, secondary navigation, and legal note on a surface tone."],
  "documentation-layout": ["Documentation layout", "Marketing presentation", "Site content", "Documentation page: navigation rail, prose article, and optional outline; navigation compacts to a wrapping list in narrow containers."],
  "active-filter-summary": ["Active filter summary","Data & productivity","Application content","Keeps active query refinements and scope visible while filter controls recompose."],
  "cluster": ["Cluster","Layout & composition","Native CSS","Wraps related inline items while preserving semantic source order."],
  "command-group": ["Command group","Navigation & commands","Application content","Groups related commands under an explicit task label without owning command authority."],
  "comparison-grid": ["Comparison grid","Layout & composition","Application content","Preserves cross-item comparison relationships in a bounded two-dimensional surface."],
  "evidence-relationship": ["Evidence relationship","Data & productivity","Application content","Makes claim-to-evidence relationship type and scope explicit rather than relying on proximity alone."],
  "feed-item": ["Feed item","Data & productivity","Application content","Compact chronological item with explicit identity, state, metadata, and owned actions."],
  "frame": ["Frame","Layout & composition","Native CSS","Constrains media to an explicit aspect ratio while keeping content contained."],
  "freshness": ["Freshness","State & feedback","Application state","Presents evidence or state age explicitly so stale and current information remain distinguishable."],
  "handoff-summary": ["Handoff summary","Assisted interaction","Application / Ordo","Exposes agent identity, proposal, uncertainty, evidence scope, and retained human authority."],
  "hierarchy-tree": ["Hierarchy tree","Navigation & commands","Native HTML / application","Uses semantic nesting and native disclosure for parent-child navigation without inventing tree behavior."],
  "landmark-region": ["Landmark region","Layout & composition","Native HTML","Creates a labeled semantic region for orientation and task ownership."],
  "lane-board": ["Lane board","Layout & workspace","Application content","Preserves item-to-lane membership in a bounded board with narrow-screen containment."],
  "measure": ["Measure","Layout & composition","Native CSS","Constrains readable line measure without changing semantic structure."],
  "navigation-shell": ["Navigation shell","Navigation & commands","Application / Limen","Preserves current location and destination identity across persistent and compact navigation modes."],
  "overflow-command-disclosure": ["Overflow command disclosure","Navigation & commands","Native HTML","Moves secondary commands into explicit native disclosure without shrinking targets or hiding group meaning."],
  "path-summary": ["Path summary","Data & productivity","Application content","Provides an ordered textual representation of a selected relationship or evidence path."],
  "relationship-index": ["Relationship index","Data & productivity","Application content","Provides a semantic non-spatial index of entity relationships and their direction."],
  "scope-trail": ["Scope trail","Navigation & commands","Application content","Keeps parent and current scope explicit as users move through nested or scaled representations."],
  "security-blockers": ["Security blockers","Security","Aegis / application","Presents security conditions that block a transition without inventing remediation authority."],
  "security-evidence-age": ["Security evidence age","Security","Aegis / application","Makes security evidence freshness and staleness explicit."],
  "security-evidence-chain": ["Security evidence chain","Security","Aegis / application","Shows the provenance chain supporting a security conclusion."],
  "security-exception": ["Security exception","Security","Aegis / application","Presents an explicit security exception, its scope, status, and governing evidence."],
  "security-invariant-result": ["Security invariant result","Security","Aegis / application","Reports invariant evaluation outcomes with explicit state rather than color-only pass/fail cues."],
  "security-posture": ["Security posture","Security","Aegis / application","Summarizes security posture while preserving unresolved, unknown, and blocking conditions."],
  "security-state-matrix": ["Security state matrix","Security","Aegis / application","Preserves security relationships across two dimensions with explicit row and column scope."],
  "security-trend": ["Security trend","Security","Aegis / application","Presents security change over time with state and context independent of color."],
  "security-unknown": ["Security unknown","Security","Aegis / application","Represents unknown security state explicitly instead of collapsing it into failure or success."],
  "sidebar": ["Sidebar","Layout & composition","Native CSS","Composes a supporting region with primary content and deterministic source-order reflow."],
  "spatial-canvas": ["Spatial canvas","Layout & workspace","Application / Limen","Provides a bounded spatial exploration surface with orientation and a non-spatial access path."],
  "split-pane": ["Split pane","Layout & workspace","Application content","Pairs related regions while preserving their semantic ownership and narrow-screen order."],
  "stack": ["Stack","Layout & composition","Native CSS","Applies consistent vertical rhythm between semantic siblings."],
  "switcher": ["Switcher","Layout & composition","Native CSS","Keeps related regions side by side when space permits and stacks them without semantic reordering."],
  "workspace-shell": ["Workspace shell","Layout & workspace","Application content","Composes navigation, primary work, contextual inspection, and status as explicit regions."],
  "emphasis-budget": ["Emphasis budget", "Layout & composition", "Application content", "Declares bounded primary, secondary, and supporting emphasis so competing regions cannot all claim the strongest visual priority."],
  "attention-path": ["Attention path", "Layout & composition", "Application content", "Declares an intended first-glance priority path while preserving semantic source order and explicit text when visual emphasis channels are removed."],
  "comparison-pairs": ["Comparison pairs", "Data & productivity", "Application content", "Before/after or peer comparison that repeats labels and preserves the comparison task when columns collapse on narrow screens."],
  "overview-disclosure": ["Overview disclosure", "Content & utility", "Application content", "Keeps consequential state, scope, uncertainty, and unresolved work visible while secondary evidence uses native disclosure."],
  "state-survivability": ["State survivability", "Status & feedback", "Ordo / application", "Projects explicit authoritative states with text and structural cues so unknown, stale, partial, and unavailable do not collapse into one generic status."],
  "identifier": ["Identifier & critical value", "Content & utility", "Application content", "Low-context identifiers, codes, numeric values, and consequential values with stronger glyph distinction and verification cues."],
  "verification-frame": ["Verification frame", "Assessment & decision", "Ordo / application", "Recognize, deliberately verify, then act without letting presentation invent authority, certainty, or legal actions."],
  "dense-ledger": ["Dense ledger", "Data & productivity", "Application content", "Compact expert-work table with bounded overflow, stable relationships, and explicit text state."],
  "focus-stage": ["Focus stage", "Layout & workspace", "Application content", "Dominant primary work surface with subordinate supporting context that stacks without semantic reordering."],
  "mosaic": ["Mosaic", "Layout & workspace", "Application content", "Asymmetric editorial composition using explicit spans and deterministic narrow-screen reflow."],
  "priority-stack": ["Priority stack", "Layout & workspace", "Application content", "Responsive composition where priority changes space allocation but never DOM or semantic order."],
  "rail": ["Rail", "Layout & workspace", "Application content", "Supporting rail plus flexible primary region with start/end placement and single-column reflow."],
  "responsive-grid": ["Responsive grid", "Layout & workspace", "Application content", "Auto-fitting composition grid with optional visual spans that collapse without changing source order."],
  "fault": ["Fault", "Aegis fault presentation", "Aegis / Ordo / Application", "Common safe presentation shell for an Aegis Presentation.T without exposing raw fault diagnostics."],
  "fault-inline": ["Fault inline", "Aegis fault presentation", "Application / Limen", "Operation-local Aegis fault presentation with reference and legal recovery actions."],
  "fault-notification": ["Fault notification", "Aegis fault presentation", "Application / Limen", "Persistent, dismissible notification surface for Aegis Notification intent; lifecycle remains application-owned."],
  "fault-banner": ["Fault banner", "Aegis fault presentation", "Application / Limen", "Persistent page/application banner for degraded or critical Aegis conditions."],
  "fault-blocking": ["Fault blocking", "Aegis fault presentation", "Application / Limen", "Native-dialog surface for Aegis Blocking intent with only application-supplied recovery actions."],
  "fault-summary": ["Fault summary", "Aegis fault presentation", "Aegis / Application", "Focusable grouped presentation of unresolved faults after upstream fingerprinting and deduplication."],
  "recovery-actions": ["Recovery actions", "Aegis fault presentation", "Aegis / Ordo / Application", "Native buttons annotated with Aegis capability identity; current authority is revalidated on activation."],
  "fault-reference": ["Fault reference", "Aegis fault presentation", "Application / Limen", "Short quotable Aegis reference with an optional application-owned copy action."],
  "diagnostic-status": ["Diagnostic status", "Aegis fault presentation", "Aegis / Application", "Text-first presentation of synchronized, queued, unavailable, or failed diagnostic persistence state."],
  "fault-details": ["Fault details", "Aegis fault presentation", "Application / Limen", "Optional disclosure for explicitly approved and already-sanitized diagnostic values only."],
  "allocation": ["Allocation", "Assessment & decision", "Application / Limen", "Distribute a bounded amount across multiple choices while preserving direct numeric entry."],
  "best-worst": ["Best–Worst", "Assessment & decision", "Application / Limen", "Capture distinct strongest and weakest choices without hiding the two-selection constraint."],
  "binary-choice": ["Binary choice", "Assessment & decision", "Native HTML", "A two-option radio-backed answer that preserves Unanswered as distinct from false."],
  "checkbox": ["Checkbox", "Input", "Native HTML", "A native checkbox with a delegated touch target, non-color checked cue, and physics-derived CSS state motion."],
  "choice-group": ["Choice group", "Selection", "Native HTML", "Semantic single-choice options with primary and supporting text."],
  "dialog": ["Dialog", "Overlay & disclosure", "Native HTML", "Modal presentation built on the platform dialog element and declarative commands."],
  "flyout": ["Flyout", "Overlay & disclosure", "Native HTML", "Left/right edge modal surface built on native dialog semantics with physics-derived motion."],
  "menu": ["Action menu", "Overlay & disclosure", "Native HTML", "A Popover-backed ordinary action list with light physics-derived motion; full ARIA menu behavior remains application-owned."],
  "disclosure": ["Disclosure", "Overlay & disclosure", "Native HTML", "Expandable content built on details and summary with no runtime behavior layer; where interpolate-size is supported the panel settles to its intrinsic height, otherwise it opens instantly."],
  "hierarchical-choice": ["Hierarchical choice", "Selection", "Native baseline / application semantics", "Nested disclosure and choice structure for hierarchy without assigning parent-child domain meaning."],
  "hierarchical-multi-choice": ["Hierarchical multi-choice", "Selection", "Application / Limen", "Multi-selection across a hierarchy with application-owned propagation and selection rules."],
  "image-choice": ["Image choice", "Selection", "Native HTML", "Choice cards that pair media with visible text while keeping the input semantic."],
  "matrix-single": ["Single-choice matrix", "Assessment & decision", "Native HTML", "Repeated single-choice scales arranged as a matrix while retaining per-row radio semantics."],
  "multi-choice": ["Multi-choice", "Selection", "Native HTML", "Checkbox-backed selection with explicit guidance for minimum, maximum, or exclusive choices."],
  "numeric-stepper": ["Numeric stepper", "Input", "Native HTML", "Bounded numeric entry using the native number input and explicit constraints."],
  "obligation-panel": ["Obligation panel", "State & feedback", "Application state", "Present unresolved work, evidence needs, and blocking status without making the design system authoritative."],
  "ordinal-scale": ["Ordinal scale", "Assessment & decision", "Native HTML", "One radio-backed contract for ordered Likert, agreement, confidence, frequency, and similar scales."],
  "pairwise-choice": ["Pairwise choice", "Assessment & decision", "Native HTML", "A focused two-alternative comparison using ordinary choice semantics."],
  "popover": ["Popover", "Overlay & disclosure", "Native HTML", "Top-layer supplemental content built on the Popover API."],
  "question": ["Question shell", "Assessment & decision", "Application content", "A stable prompt, help, selector, and validation structure for assessment questions."],
  "range-entry": ["Range entry", "Input", "Native HTML", "Direct lower/upper endpoint entry; graphical dual-thumb behavior is an optional application enhancement."],
  "ranking": ["Ranking", "Assessment & decision", "Application / Limen", "Ordered-choice presentation with non-drag movement controls and visible positions."],
  "rule-builder": ["Rule builder", "Advanced input", "Application / Limen", "Field/operator/value clauses for typed rule editing while the application owns expression semantics."],
  "segmented-control": ["Segmented control", "Selection", "Native HTML", "Radio-backed compact selection with visible selected and focus states; where supported, one light-inertial selection indicator travels between segments without delaying native selection."],
  "semantic-differential": ["Semantic differential", "Assessment & decision", "Native HTML", "A bipolar textual scale that keeps the ordered response radio-backed and explicit."],
  "slider": ["Slider", "Input", "Native HTML", "Single-value range input with accessible bounds and direct keyboard/pointer control."],
  "special-choice": ["Special choice", "Assessment & decision", "Native HTML", "Unknown, not-applicable, and other non-scale answers visually separated from the primary continuum."],
  "survey-progress": ["Survey progress", "State & feedback", "Native HTML", "Determinate progress using the native progress element plus explicit current/total text."],
  "switch": ["Switch", "Input", "Native HTML", "A checkbox-backed on/off preference control with role=switch and a visible track/thumb treatment."],
  "symbol-rating": ["Symbol rating", "Assessment & decision", "Native HTML", "Ordinal rating presented with symbols while retaining accessible textual labels."],
  "validation-message": ["Validation message", "State & feedback", "Application state", "Question-level recovery guidance with icon, text, and non-color signaling."],
  "validation-summary": ["Validation summary", "State & feedback", "Application state", "Focusable page-level error summary with links back to affected controls."],
  "alert": ["Alert", "State & feedback", "Application state", "Structured status or warning communication with text, icon, and non-color cues."],
  "collection-toolbar": ["Collection toolbar", "Data & productivity", "Application / Limen", "A responsive composition for search, filters, sort, saved views, and result counts."],
  "combobox": ["Combobox", "Input", "Native baseline / Limen enhancement", "Searchable selection baseline that preserves direct text entry and native semantics."],
  "composer": ["Composer", "Assisted interaction", "Application / Limen", "Natural-language composition surface for type, dictate, paste, and attach workflows without embedding agent behavior."],
  "command-palette": ["Command palette", "Navigation & commands", "Application / Limen", "Keyboard-first command discovery that can become a full-screen mobile surface."],
  "conflict-review": ["Conflict review", "State & feedback", "Ordo / application", "Explain optimistic-concurrency conflicts and expose application-supplied recovery actions without guessing."],
  "conversation": ["Conversation", "Assisted interaction", "Application / Limen", "Inspectable user/application turns with explicit speakers and no consumer-chat authority assumptions."],
  "dashboard-grid": ["Dashboard grid", "Layout & workspace", "Application content", "Responsive operational dashboard composition for metrics, status, and attention-first blocks."],
  "data-grid": ["Data grid", "Data & productivity", "Application / Limen", "Semantic tabular records with sortable affordances and a labeled mobile record projection."],
  "date-range": ["Date range", "Input", "Native HTML / application", "Paired direct date entry with reusable preset affordances and mobile stacking."],
  "diff-viewer": ["Diff viewer", "Data & productivity", "Application content", "Before/after structured differences with explicit changed-field cues and stacked mobile comparison."],
  "empty-state": ["Empty state", "State & feedback", "Application content", "Explain an empty result and provide a useful recovery action without treating absence as failure."],
  "file-upload": ["File upload queue", "Input", "Native HTML / Limen", "Native file selection plus a reusable upload queue for progress, success, cancellation, failure, and unknown outcomes."],
  "master-detail": ["Master/detail workspace", "Layout & workspace", "Application / Limen", "List-and-detail composition that collapses cleanly from multi-pane desktop to mobile navigation."],
  "metric-value-change": ["Metric value change", "Content & utility", "Application state", "A metric whose authoritative value updates immediately; a neutral perceptual tint marks the update without counting through invented numbers or implying direction."],
  "metric-card": ["Metric card", "Content & utility", "Application content", "A compact labeled value with context and optional action, without inventing metric meaning."],
  "mobile-action-bar": ["Mobile action bar", "Navigation & commands", "Application / Limen", "Safe-area-aware mobile action region for critical contextual actions."],
  "operation-status": ["Operation status", "State & feedback", "Ordo / application", "Present pending, confirmed, failed, conflict, unknown, reconciling, stale, blocked, unavailable, or insufficient states."],
  "pagination": ["Pagination", "Navigation & commands", "Application / Limen", "Page navigation with explicit current-page semantics and compact mobile presentation."],
  "preview-surface": ["Preview surface", "Layout & workspace", "Application content", "A bounded review surface for consequential content before an application commits or publishes it."],
  "provenance-trail": ["Provenance trail", "Data & productivity", "Application content", "Trace displayed output through source, aggregate, analysis, and presentation stages."],
  "readiness-checklist": ["Readiness checklist", "State & feedback", "Ordo / application", "Explicit complete, incomplete, and blocking prerequisites before a consequential transition."],
  "record-header": ["Record header", "Layout & workspace", "Application content", "Persistent record identity, status, context, breadcrumbs, and legal actions with mobile action collapse."],
  "search": ["Search", "Input", "Application / Limen", "Search entry, clearing, and result-count feedback with asynchronous behavior owned by the application."],
  "select": ["Select", "Input", "Native HTML", "An ordinary native select with platform picker behavior and physics-derived CSS affordance motion."],
  "scroll-progress": ["Scroll progress", "State & feedback", "Native HTML", "Decorative reading-progress bar driven directly by the scroll timeline: no smoothing or lag, absent without scroll timelines or under reduced motion."],
  "skeleton": ["Skeleton", "State & feedback", "Application state", "Low-information loading placeholder with explicit busy semantics; its shimmer is a named cadence that runs only while aria-busy is true and stops for reduced motion."],
  "resizable-split-pane": ["Resizable split pane", "Layout", "Application / Limen", "Split pane whose application-supplied size tracks drag or keys directly, settles without overshoot, and is clamped to legal bounds in CSS."],
  "reorder-states": ["Reorder states", "Data & productivity", "Application / Limen", "Presentation hooks for dragging, displaced siblings, drop candidates, accepted/rejected drops and post-release settling."],
  "tooltip": ["Tooltip / contextual hint", "Overlay", "Native HTML", "Supplemental hint on a native button: opens by click, tap or keyboard (popovertarget) and, where supported, on hover or focus (interestfor); light motion with a static reduced-motion substitute."],
  "spinner": ["Spinner", "State & feedback", "Application state", "Indeterminate activity with a visible label: constant-velocity cadence that stops when the application marks the activity idle, static under reduced motion."],
  "progress-bar": ["Progress bar", "State & feedback", "Native HTML", "Native determinate progress projected directly from the authoritative value (never overshoots), plus a browser-owned indeterminate variant with explicit text."],
  "status-lozenge": ["Status lozenge", "Content & utility", "Application state", "Compact textual state labels with structural and non-color cues."],
  "tabs": ["Tabs", "Navigation & commands", "Application / Limen", "Focused views with keyboard and deep-link integration hooks plus mobile overflow strategy."],
  "toast": ["Toast", "State & feedback", "Native HTML", "A Popover-backed transient notification with standard perceived weight and a shorter derived dismissal."],
  "timeline": ["Timeline", "Data & productivity", "Application content", "Chronological or ordered activity with timestamps, state changes, provenance, and single-column mobile flow."],
  "understanding": ["Understanding review", "Assisted interaction", "Ordo / application", "Review proposed understanding, unknowns, conflicts, and source actions before consequential transitions."],
  "wizard": ["Wizard", "Navigation & commands", "Limen / Ordo", "Step-by-step workflow shell with current-step state, progress, validation hooks, resume, and mobile reduction."],
  "character-grid": ["Character grid", "Layout & workspace", "Application / Limen", "Fixed rows-by-columns grid of equal-width cells where every run declares its cell coordinates and source order is row-major order; contained horizontal scroll by default."],
  "character-grid-field": ["Character grid field", "Input", "Native HTML", "Protected text and native editable fields placed on a character grid with explicit capacity, preceding labels, and shape-based required, invalid, disabled, and read-only cues."],
  "character-grid-keys": ["Character grid keys", "Navigation & commands", "Application / Limen", "Enter, Clear, Reset, PF1-PF24, and named action affordances as native buttons with visible key names; the application owns what each key does."],
  "character-grid-status": ["Character grid status", "State & feedback", "Application state", "Message and system-status live regions on a character grid with a visible severity word and shape cues that survive forced colors."],
  "character-grid-reveal": ["Character grid reveal", "Motion & presentation", "Application / Limen", "Optional SequentialReveal presentation: a row-major clip mask over protected text already in the DOM, static by default and under reduced motion; orchestration stays in the application."],
  "character-grid-selection": ["Character grid selection", "Input", "Application / Limen", "Per-row selection fields in positioned repeated rows (a 5250-style option column): native text inputs named by their column and row headers and described by the option legend; the application owns what each option does."],
  "character-grid-3270": ["Character grid 3270 profile", "Layout & workspace", "Application / Limen", "IBM 3270-inspired reference profile built only from public CharacterGrid contracts: a 24x80 operations menu with 3279-style palette tokens and block caret, verified at 32x80."],
  "character-grid-workflow": ["Character grid workflow", "Layout & workspace", "Application / Limen / Ordo", "Customer Inquiry, Account Detail, and Transaction History built only from public CharacterGrid contracts; transitions stay in the application."],
  "work-queue": ["Work queue", "State & feedback", "Ordo / application", "Attention-first list of unresolved work with reason, context, and application-supplied legal actions."]
};
