// Generates docs/COMPONENT-INVENTORY.md from the catalog, the stylesheet,
// the test suite and catalog/planned.json + catalog/known-issues.json.
//
//   node tools/catalog/inventory.mjs          # write the document
//   node tools/catalog/inventory.mjs --check  # fail if it is out of date
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { loadCatalog } from "./load.mjs";
import { patternOnlyClasses, validateComponent } from "./validate.mjs";

const TARGET = "docs/COMPONENT-INVENTORY.md";

const readJson = file => (fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, "utf8")) : {});

const testSources = root => [
  ...fs.readdirSync(path.join(root, "tests")).filter(file => file.endsWith(".mjs")).map(file => `tests/${file}`),
  ...fs.readdirSync(path.join(root, "tests", "browser")).filter(file => file.endsWith(".mjs")).map(file => `tests/browser/${file}`)
].map(file => ({ file, text: fs.readFileSync(path.join(root, file), "utf8") }));

// Tests that name the component's pattern, slug or owned CSS block.
export const dedicatedTests = (sources, component) =>
  sources
    .filter(({ file, text }) => !/catalog-coverage|site-build|figma-contract|zero-runtime|package-contract/.test(file))
    .filter(({ text }) =>
      text.includes(`patterns/${component.slug}.html`) ||
      // `(?<!html)` keeps compiled icon assets such as `icons/html/search.html`
      // from being read as a reference to the same-named component pattern.
      new RegExp(`(?<!html)/${component.slug}\\.html`).test(text) ||
      component.owns.some(root => new RegExp(`\\.${root}(?![a-z0-9-])`).test(text)))
    .map(({ file }) => path.basename(file));

const mark = ok => (ok ? "yes" : "**no**");
const cell = value => String(value).replaceAll("|", "\\|");

export const renderInventory = (catalog, root) => {
  const sources = testSources(root);
  const planned = readJson(path.join(root, "catalog", "planned.json")).planned ?? [];
  const issues = readJson(path.join(root, "catalog", "known-issues.json")).issues ?? [];
  const categoryName = new Map(catalog.categories.map(category => [category.id, category.name]));
  const rows = catalog.categories.flatMap(category => category.components.map(component => {
    const problems = validateComponent(catalog, component);
    const scenarios = component.examples.filter(example => !example.mobile).length;
    const mobiles = component.examples.filter(example => example.mobile).length;
    const tests = dedicatedTests(sources, component);
    return `| ${cell(component.name)} | \`<${component.tag}>\` | ${cell(category.name)} | ${component.pattern ? "implemented" : "**missing pattern**"} | ${problems.length ? `**${problems.length} gaps**` : "complete"} | ${scenarios + 1} | ${mobiles} | ${mark(component.examples.every(example => example.html))} | ${mark(component.accessibility?.forma?.length)} | ${mark(component.api)} | ${tests.length ? cell(tests.join(", ")) : "generic only"} | ${cell((component.related ?? []).map(item => item.slug).join(", "))} |`;
  }));
  return `<!-- Generated by tools/catalog/inventory.mjs. Do not edit by hand; run \`npm run catalog:inventory\`. -->
# Forma component inventory

This is the durable inventory of every public Forma component, generated from
the component catalog (\`catalog/components/*.mjs\`), the canonical patterns
(\`patterns/*.html\`), the built stylesheet and the test suite. The catalog
checker (\`npm run catalog:check\`) fails when a canonical pattern or a public
\`.ef-*\` block class is missing from this list.

- Public components: **${catalog.components.length}** in **${catalog.categories.length}** families
- Live examples on the documentation site: **${catalog.components.reduce((total, component) => total + component.examples.length + 1, 0)}** (each component: canonical Basic + scenario examples + mobile examples)
- Compositions: **${catalog.compositions.length}** (${catalog.compositions.map(item => item.title).join(", ")})
- Requirement-defined components not yet implemented: **${planned.length}**

## How the inventory was established

1. Every file in \`patterns/*.html\` (the public, packaged markup contracts).
2. Every CSS block class in \`dist/all.css\` (\`src/styles\` and \`src/marketing\`). Each must be owned by exactly one catalog entry; this found fourteen styled primitives that had no page (button, text field, textarea, date and time field, surface, grid, section, key-value list, visually hidden, bounded overflow, container, split, skip link, text roles), which now have canonical patterns and pages.
3. \`requirements/COMPONENT-CATALOG.md\` and the family requirements (Aegis, CharacterGrid, marketing, Tutela security, selector completeness, object metadata and diagrams) for components that are required but not implemented (listed below, not documented as usable).
4. \`figma/component-contracts.json\`, which must cover every pattern.

Columns: *Examples* counts the canonical Basic example plus scenario examples; *Mobile* counts explicit mobile examples rendered in a real narrow viewport. Every component is also covered by the generic suites: pattern mobile containment and touch targets (\`tests/browser/mobile.spec.mjs\`), catalog coverage (\`tests/catalog-coverage.test.mjs\`) and generated-site containment, zoom and axe checks (\`tests/site-browser/\`). *Dedicated tests* lists additional specs that name the component.

## Implemented components

| Component | Tag | Category | Implementation | Documentation | Examples | Mobile | HTML shown | Accessibility | API | Dedicated tests | Related |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
${rows.join("\n")}

## Categories

${catalog.categories.map(category => `- **${category.name}** (\`/components/${category.id}/\`, ${category.components.length}): ${category.summary}`).join("\n")}

## Required but not implemented

These appear in requirements but have no markup contract yet, so they have no catalog page. Source: \`catalog/planned.json\`.

| Component | Family | Priority | Requirement | Note |
| --- | --- | --- | --- | --- |
${planned.map(item => `| ${cell(item.name)} | ${cell(categoryName.get(item.category) ?? item.category)} | ${item.priority} | ${cell(item.requirement)} | ${cell(item.note || "—")} |`).join("\n")}

## Unstyled pattern hooks

Classes used by canonical patterns that no Forma CSS rule styles. They are part of the published markup and are accepted in examples, but they carry no presentation:

${patternOnlyClasses(catalog).map(name => `- \`.${name}\``).join("\n")}

## Known issues found while documenting

Recorded from reading every pattern and its CSS during the catalog upgrade (WI-0011). Source: \`catalog/known-issues.json\`. Each is a candidate work item; none was changed as part of the documentation work unless noted.

| Component | Issue | Location |
| --- | --- | --- |
${issues.map(item => `| ${cell(item.component)} | ${cell(item.issue)} | ${cell(item.location ?? "—")} |`).join("\n")}
`;
};

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const root = process.cwd();
  const document = renderInventory(await loadCatalog(root), root);
  if (process.argv.includes("--check")) {
    const current = fs.existsSync(path.join(root, TARGET)) ? fs.readFileSync(path.join(root, TARGET), "utf8") : "";
    if (current !== document) {
      console.error(`${TARGET} is out of date. Run npm run catalog:inventory.`);
      process.exitCode = 1;
    } else {
      console.log(`${TARGET} is current.`);
    }
  } else {
    fs.writeFileSync(path.join(root, TARGET), document);
    console.log(`Wrote ${TARGET}.`);
  }
}
