export default {
  name: "Scope trail",
  category: "navigation",
  behavior: "Application content",
  summary: "Keeps parent and current scope explicit as users move through nested or scaled representations.",
  purpose: {
    description: "A scope trail states where the user is: each ancestor scope as a link and the current scope as plain text marked `aria-current=\"page\"`. It is a labelled `nav` with an ordered list; Forma lays the items out as a wrapping row with a slash drawn between them. It is used for ordinary nested records (System / Billing / Invoice 1042) and for scaled or zoomed representations, where the trail keeps the parent scope explicit while the view changes. The application supplies the ancestors and URLs.",
    useWhen: [
      "Users drill into nested objects and need a way back to each parent.",
      "A zoomable or scaled view (map, diagram, canvas) needs the current scope stated in text.",
      "The current location must be available to assistive technology, not only implied by the view."
    ],
    avoidWhen: [
      "Navigating between sibling pages of a result set: use [[pagination]].",
      "Showing a whole hierarchy to browse: use [[hierarchy-tree]].",
      "Showing progress through a process: use [[wizard]] or [[steps]].",
      "Recording where a value came from: use [[provenance-trail]]."
    ],
    characteristics: [
      "Ordered list semantics communicate depth; the slash separator is generated by CSS.",
      "The current scope is text, not a link, so it cannot be activated to reload itself.",
      "Items wrap onto several lines instead of truncating or scrolling.",
      "No visual styling beyond layout; links use the theme's link treatment."
    ]
  },
  examples: [
    {
      id: "deep-record",
      title: "Deeply nested record with long names",
      description: "Five levels with long names. The row wraps between items; every ancestor stays a real link and the current scope is plain text.",
      html: `<ef-scope-trail class="ef-component-tag">
  <nav class="ef-scope-trail" aria-label="Current scope">
    <ol>
      <li><a href="#scope-deep-org">Northwind Holdings</a></li>
      <li><a href="#scope-deep-region">Europe, Middle East and Africa</a></li>
      <li><a href="#scope-deep-account">Northwind Logistics GmbH</a></li>
      <li><a href="#scope-deep-contract">Master services agreement 2026</a></li>
      <li aria-current="page">Amendment 3: data processing terms</li>
    </ol>
  </nav>
</ef-scope-trail>`
    },
    {
      id: "zoomed-diagram",
      title: "Scope of a zoomed diagram",
      description: "In a zoomable architecture diagram the trail states the current zoom scope in text, followed by a heading for the current representation. Selecting an ancestor zooms back out.",
      html: `<ef-scope-trail class="ef-component-tag">
  <nav class="ef-scope-trail" aria-label="Diagram scope">
    <ol>
      <li><a href="#scope-zoom-system">All systems</a></li>
      <li><a href="#scope-zoom-checkout">Checkout</a></li>
      <li aria-current="page">Payment gateway components</li>
    </ol>
  </nav>
  <h2>Payment gateway components</h2>
  <p>Showing 6 components inside Payment gateway. Zoom out to see how Checkout connects to Inventory.</p>
</ef-scope-trail>`
    },
    {
      id: "mobile-wrapping-trail",
      title: "Scope trail on a phone",
      description: "Four levels at phone width. Items wrap onto a second line; the separator stays at the start of each continued item.",
      mobile: {
        height: 200,
        notes: [
          "The list is a wrapping flex row, so items continue on new lines instead of truncating or scrolling.",
          "Each separator belongs to the item after it, so a wrapped line starts with a slash, keeping the hierarchy readable.",
          "Long names wrap at spaces within their item, and link text can also break inside very long words.",
          "Links keep their inline text size; on touch-heavy pages give them extra padding in application styling, since Forma does not enforce 44px targets here."
        ]
      },
      html: `<ef-scope-trail class="ef-component-tag">
  <nav class="ef-scope-trail" aria-label="Folder scope">
    <ol>
      <li><a href="#scope-mobile-drive">Shared drive</a></li>
      <li><a href="#scope-mobile-finance">Finance</a></li>
      <li><a href="#scope-mobile-2026">2026 year-end close</a></li>
      <li aria-current="page">Reconciliations</li>
    </ol>
  </nav>
</ef-scope-trail>`
    }
  ],
  api: {
    attributes: [
      { name: "aria-label", on: "nav", values: "string", default: "—", description: "Names the landmark, for example Current scope. Use a distinct label if a page has several trails." },
      { name: "aria-current", on: "last li", values: "page", default: "absent", description: "Marks the current scope. Put it on the plain-text item, not on a link to the same page." },
      { name: "href", on: "ancestor links", values: "URL", default: "—", description: "Real URLs for each ancestor scope, supplied by the application." }
    ],
    hooks: {
      "ef-scope-trail": "Root nav. Its ordered list becomes a wrapping flex row with small gaps and a CSS-generated slash before every item after the first."
    },
    keyboard: [
      { keys: "Tab / Shift+Tab", action: "Moves through the ancestor links; the current scope is text and is not focusable." },
      { keys: "Enter", action: "Follows the focused link (native)." }
    ],
    events: [],
    form: "Does not participate in forms."
  },
  states: [
    { name: "Ancestor", how: "li containing a link", description: "Rendered with the theme's link style." },
    { name: "Current", how: "aria-current=\"page\" on plain text", description: "Unlinked text. Forma adds no extra highlight; the absence of a link distinguishes it." },
    { name: "Wrapped", how: "narrow container", description: "Items continue on the next line." }
  ],
  accessibility: {
    forma: [
      "Keeps list semantics so the number of levels and position are available to assistive technology.",
      "Draws separators with CSS rather than text in the markup."
    ],
    consumer: [
      "Provide the full ancestor chain with meaningful, unique names.",
      "Keep the current scope in text and mark it with aria-current.",
      "Update the trail and the page heading together when the scope changes, and move focus to the heading after a scope change in a single-page application."
    ]
  },
  responsive: [
    "A wrapping flex row with 0.25rem row and 0.5rem column gaps.",
    "No truncation or collapsing; very deep trails simply take more lines.",
    "No breakpoints."
  ],
  motion: [
    "No animation: the trail is static text and links."
  ],
  guidance: {
    do: [
      "Use the same names in the trail as in the headings users arrive at.",
      "Place the trail directly above the heading of the current scope."
    ],
    avoid: [
      "Linking the current scope to itself.",
      "Using the trail as the only indication of scope in a zoomed view; also state it in the heading."
    ]
  },
  related: [
    { slug: "hierarchy-tree", note: "Shows the whole hierarchy for browsing, not just the current path." },
    { slug: "spatial-canvas", note: "Zoomable representation that a scope trail commonly accompanies." },
    { slug: "provenance-trail", note: "Records where a value came from, not where the user is." },
    { slug: "pagination", note: "Moves between pages of results at the same level." }
  ]
};
